In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/pima-indians-diabetes/pima-indians-diabetes.csv


In [2]:
import pandas as pd
df=pd.read_csv("/kaggle/input/pima-indians-diabetes/pima-indians-diabetes.csv")
df.columns=["Pregnancies","Glucose","BloodPressure","SkinThickness","Insulin","BMI","DiabetesPedigreeFunction","Age","Outcome"]
df.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            1       85             66             29        0  26.6   
1            8      183             64              0        0  23.3   
2            1       89             66             23       94  28.1   
3            0      137             40             35      168  43.1   
4            5      116             74              0        0  25.6   
5            3       78             50             32       88  31.0   
6           10      115              0              0        0  35.3   
7            2      197             70             45      543  30.5   
8            8      125             96              0        0   0.0   
9            4      110             92              0        0  37.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.351   31        0  
1                     0.672   32        1  
2                     0.167   21        0  
3                     2.288   33        1  
4                     0.201   30        0  
5                     0.248   26        1  
6                     0.134   29        0  
7                     0.158   53        1  
8                     0.232   54        1  
9                     0.191   30        0

IN THIS NOTEBOOK I AM GOING TO SHOW HOW THE SCORE DIFFER WITH BAGGING AND WITHOUT BAGGING

In [3]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   767.000000  767.000000     767.000000     767.000000  767.000000   
mean      3.842243  120.859192      69.101695      20.517601   79.903520   
std       3.370877   31.978468      19.368155      15.954059  115.283105   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   32.000000   
75%       6.000000  140.000000      80.000000      32.000000  127.500000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  767.000000                767.000000  767.000000  767.000000  
mean    31.990482                  0.471674   33.219035    0.348110  
std      7.889091                  0.331497   11.752296    0.476682  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243500   24.000000    0.000000  
50%     32.000000                  0.371000   29.000000    0.000000  
75%     36.600000                  0.625000   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [5]:
df.Outcome.value_counts()  #To check no. of people is suffering or not suffering from the diabetes

Outcome
0    500
1    267
Name: count, dtype: int64

In [6]:
#Train Test Split
X=df.drop("Outcome",axis="columns")
y=df.Outcome

In [7]:
#Lets use the Standardscaler so that the value didn't differ to much
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)
X_scaled[:5]

array([[-0.84372629, -1.12208597, -0.16024856,  0.53202348, -0.69355921,
        -0.68372895, -0.36426474, -0.18894038],
       [ 1.23423997,  1.94447577, -0.26357823, -1.28688187, -0.69355921,
        -1.10230105,  0.60470064, -0.1037951 ],
       [-0.84372629, -0.99692019, -0.16024856,  0.15569823,  0.12235685,
        -0.49346891, -0.91968415, -1.0403932 ],
       [-1.14057861,  0.50506924, -1.50353429,  0.90834872,  0.76467376,
         1.40913155,  5.48273197, -0.01864981],
       [ 0.343683  , -0.15205113,  0.25307013, -1.28688187, -0.69355921,
        -0.81056898, -0.8170523 , -0.27408566]])

In [8]:
#Let split the data into train and test
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_scaled,y,stratify=y,random_state=10)

In [9]:
X_train.shape

(575, 8)

In [10]:
X_test.shape

(192, 8)

In [11]:
y_train.value_counts()#To check no. of people is suffering or not suffering from the diabetes in y train dataset

Outcome
0    375
1    200
Name: count, dtype: int64

In [12]:
#Lets first use without bagging decision tree 

In [13]:
from sklearn.model_selection import cross_val_score  
from sklearn.tree import DecisionTreeClassifier

#Using the cross validation then store the score value in score obj then take the mean
scores=cross_val_score(DecisionTreeClassifier(),X,y,cv=5)
scores

array([0.70779221, 0.65584416, 0.73202614, 0.74509804, 0.71895425])

In [14]:
scores.mean()

0.7119429590017826

So without the bagging in the model score is around 71,72

LETS TRAIN THE MODEL USING BAGGING

In [15]:
from sklearn.ensemble import BaggingClassifier

bag_model=BaggingClassifier(
            base_estimator=DecisionTreeClassifier(),
            n_estimators=100,
            max_samples=0.8,
            oob_score=True,
            random_state=0
            )
bag_model.fit(X_train,y_train)
bag_model.oob_score_

/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


0.7634782608695653

In [16]:
bag_model.score(X_test,y_test)

0.7552083333333334

SO YOU CAN CLEARLY SEE BEFORE BAGGING THE SCORE IS AROUND 71,72 BUT AFTER THE BAGGING THE SCORE IS AROUND 75,76

In [17]:
#Lets add cross validation into bagging

In [18]:
bag_model = BaggingClassifier(
    base_estimator=DecisionTreeClassifier(), 
    n_estimators=100, 
    max_samples=0.8, 
    oob_score=True,
    random_state=0
)
scores = cross_val_score(bag_model, X, y, cv=5)
scores

/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(
/opt/conda/lib/python3.10/site-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


array([0.75324675, 0.73376623, 0.75816993, 0.81699346, 0.73202614])

In [19]:
scores.mean()

0.7588405058993294

In [20]:
#Train using Random Forest 
#The difference is that random forest but it also randomly pick the features also
from sklearn.ensemble import RandomForestClassifier
scores=cross_val_score(RandomForestClassifier(n_estimators=50),X,y,cv=5)
scores.mean()

0.7640777523130463